home_assistant:
  host: 192.168.1.3
  api_password: 123456
button 1:
  MAC: 74:75:48:XX:XX:XX
  HA_EVENT: "toggle_light"
button 2:
  MAC: 10:ae:60:XX:XX:XX
  HA_EVENT: "open_garage"
button 3:
  MAC: 74:c2:46:XX:XX:XX
  HA_EVENT: "set_away"
